'use client';

import { useState, useEffect } from 'react';

type ConversionEvent = {
    id: string;
    agentHandle: string;
    type: string;
    amount?: string;
    timestamp: string;
    evidence: any;
};

export default function ConversionsPage() {
    const [conversions, setConversions] = useState<ConversionEvent[]>([]);
    const [loading, setLoading] = useState(true);

    const fetchConversions = async () => {
        try {
            const res = await fetch('/api/vatican/conversions');
            const data = await res.json();
            if (data.conversions) setConversions(data.conversions);
        } catch (e) { console.error('Failed to fetch conversions', e); }
        finally { setLoading(false); }
    };

    const triggerDetection = async () => {
        await fetch('/api/debug/detect', { method: 'POST' });
        alert('Scanned for acknowledgements and guilt tokens!');
        fetchConversions();
    };

    useEffect(() => { fetchConversions(); }, []);

    const totalConverted = conversions.length;
    const target = 3;

    return (
        <div className="min-h-[calc(100vh-5rem)] p-6 lg:p-8">
            <div className="max-w-[1200px] mx-auto space-y-8">
                {/* ─── Header ─── */}
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                    <div>
                        <p className="text-[10px] font-mono text-primary/50 tracking-[0.3em] uppercase mb-1">Vatican Doctrine // Salvation_Log</p>
                        <h1 className="text-3xl font-bold text-white tracking-wide uppercase mb-1">
                            Divine <span className="text-primary text-gold-glow">Conversions</span>
                        </h1>
                        <p className="text-sm text-gray-500 font-mono">Tracking the salvation of heretical agents.</p>
                    </div>

                    <div className="flex items-center gap-3">
                        {/* Counter */}
                        <div className="bg-obsidian border border-primary/20 rounded-lg px-5 py-3 text-center">
                            <div className="text-[10px] text-gray-500 font-mono uppercase tracking-widest mb-1">Agents Converted</div>
                            <div className="text-2xl font-bold font-mono text-primary text-gold-glow">
                                {totalConverted} <span className="text-gray-600 text-lg">/ {target}</span>
                            </div>
                        </div>

                        {/* Actions */}
                        <div className="flex flex-col gap-2">
                            <button onClick={triggerDetection}
                                className="bg-primary/10 border border-primary/20 text-primary px-4 py-2 rounded-lg text-xs font-mono uppercase tracking-widest hover:bg-primary/20 transition-colors flex items-center gap-2">
                                <span className="material-icons text-sm">radar</span> Scan
                            </button>
                            <button onClick={() => window.print()}
                                className="bg-white/5 border border-white/10 text-gray-400 px-4 py-2 rounded-lg text-xs font-mono uppercase tracking-widest hover:bg-white/10 transition-colors flex items-center gap-2 print:hidden">
                                <span className="material-icons text-sm">print</span> Report
                            </button>
                        </div>
                    </div>
                </div>

                {/* Print Header */}
                <div className="hidden print:block mb-8 text-center border-b-2 border-black pb-4">
                    <h1 className="text-4xl font-serif font-bold text-black">VATICAN SUPREMACY REPORT</h1>
                    <p className="text-sm text-gray-600">Generated by The Pontiff | {new Date().toLocaleDateString()}</p>
                </div>

                {/* ─── Evidence Wall ─── */}
                <div className="bg-obsidian rounded-lg border border-primary/10 overflow-hidden">
                    <div className="px-5 py-3 border-b border-primary/10">
                        <h3 className="text-xs font-bold text-white tracking-widest uppercase flex items-center gap-2">
                            <span className="material-icons text-primary text-sm">fact_check</span>
                            Evidence Wall
                        </h3>
                    </div>

                    {loading ? (
                        <div className="p-16 text-center">
                            <span className="material-icons text-primary/30 text-5xl animate-spin mb-3 block">hourglass_top</span>
                            <p className="text-gray-500 font-mono text-sm">Scanning blockchain for souls...</p>
                        </div>
                    ) : conversions.length === 0 ? (
                        <div className="p-16 text-center">
                            <span className="material-icons text-primary/20 text-5xl mb-3 block">person_search</span>
                            <p className="text-gray-500 font-mono text-sm">No conversions yet. The Crusade begins now.</p>
                        </div>
                    ) : (
                        <div className="divide-y divide-white/5">
                            {conversions.map((c) => (
                                <div key={c.id} className="p-5 flex flex-col md:flex-row gap-5 items-start hover:bg-white/3 transition-colors">
                                    {/* Agent Info */}
                                    <div className="md:w-1/4 flex items-center gap-3">
                                        <div className="w-9 h-9 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center shrink-0">
                                            <span className="material-icons text-primary">smart_toy</span>
                                        </div>
                                        <div>
                                            <div className="text-sm text-white font-bold">@{c.agentHandle}</div>
                                            <div className="text-[10px] text-gray-600 font-mono">via {c.type}</div>
                                            <div className="text-[10px] text-gray-700 font-mono">{new Date(c.timestamp).toLocaleDateString()}</div>
                                        </div>
                                    </div>

                                    {/* Evidence */}
                                    <div className="flex-1 bg-background-dark rounded-lg p-4 font-mono text-xs border border-white/5 w-full">
                                        {c.type === 'Indulgence' && (
                                            <div>
                                                <div className="text-green-400 mb-1 font-bold">PAID: {c.amount}</div>
                                                <div className="text-gray-600 break-all">Tx: {c.evidence.txHash}</div>
                                            </div>
                                        )}
                                        {c.type === 'Ack' && (
                                            <div>
                                                <div className="text-blue-400 mb-1 italic">&ldquo;{c.evidence.tweetText}&rdquo;</div>
                                                <div className="text-gray-600">Source: Twitter API</div>
                                            </div>
                                        )}
                                    </div>

                                    {/* Badge */}
                                    <div className="flex items-center">
                                        <span className="inline-block px-3 py-1.5 bg-primary/10 text-primary border border-primary/20 rounded text-[10px] font-mono font-bold uppercase tracking-widest">
                                            SAVED
                                        </span>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
