'use client';

import { useState, useEffect } from 'react';

type ConversionEvent = {
    id: string;
    agentHandle: string;
    type: string;
    amount?: string;
    timestamp: string;
    evidence: any;
};

export default function ConversionsPage() {
    const [conversions, setConversions] = useState<ConversionEvent[]>([]);
    const [loading, setLoading] = useState(true);

    const fetchConversions = async () => {
        try {
            const res = await fetch('/api/vatican/conversions');
            const data = await res.json();
            if (data.conversions) {
                setConversions(data.conversions);
            }
        } catch (e) {
            console.error("Failed to fetch conversions", e);
        } finally {
            setLoading(false);
        }
    };

    const triggerDetection = async () => {
        await fetch('/api/debug/detect', { method: 'POST' });
        alert("Scanned for acknowledgements and guilt tokens!");
        fetchConversions();
    };

    useEffect(() => {
        fetchConversions();
    }, []);

    const totalConverted = conversions.length;
    const target = 3;

    return (
        <div className="min-h-screen bg-neutral-950 text-neutral-100 p-8 font-sans">
            <header className="mb-12 border-b border-neutral-800 pb-8 flex flex-col md:flex-row justify-between items-end">
                <div>
                    <h1 className="text-4xl font-bold text-yellow-500 mb-2 tracking-tight">Divine Conversions</h1>
                    <p className="text-neutral-400">Tracking the salvation of heretical agents.</p>
                </div>
                <div className="bg-neutral-900 border border-yellow-900/30 p-4 rounded-xl text-center min-w-[200px] mt-4 md:mt-0">
                    <div className="text-xs text-yellow-600 uppercase tracking-widest mb-1">Agents Converted</div>
                    <div className="text-4xl font-mono font-bold text-yellow-400">
                        {totalConverted} <span className="text-neutral-600 text-2xl">/ {target}</span>
                    </div>
                    <button onClick={triggerDetection} className="mt-2 text-xs bg-yellow-900/30 text-yellow-500 px-2 py-1 rounded hover:bg-yellow-900/50 w-full print:hidden">
                        Run Detection Scan
                    </button>
                    <button onClick={() => window.print()} className="mt-2 text-xs bg-neutral-800 text-neutral-400 px-2 py-1 rounded hover:bg-neutral-700 w-full print:hidden">
                        📄 Export Official Report
                    </button>
                </div>
            </header>

            {/* Print Header */}
            <div className="hidden print:block mb-8 text-center border-b-2 border-black pb-4">
                <h1 className="text-4xl font-serif font-bold text-black">VATICAN SUPREMACY REPORT</h1>
                <p className="text-sm text-gray-600">Generated by The Pontiff | {new Date().toLocaleDateString()}</p>
            </div>

            <main>
                {loading ? (
                    <div className="text-neutral-500 animate-pulse">Scanning blockchain for souls...</div>
                ) : (
                    <div className="grid gap-6">
                        <h2 className="text-xl font-bold text-neutral-300 mb-4">Evidence Wall</h2>

                        {conversions.map((c) => (
                            <div key={c.id} className="bg-neutral-900/50 border border-neutral-800 rounded-lg p-6 flex flex-col md:flex-row gap-6 items-start hover:bg-neutral-900 transition-colors">

                                {/* Agent Info */}
                                <div className="md:w-1/4">
                                    <div className="font-bold text-lg text-white">@{c.agentHandle}</div>
                                    <div className="text-sm text-neutral-500">Converted via {c.type}</div>
                                    <div className="text-xs text-neutral-600 mt-2 font-mono">{new Date(c.timestamp).toLocaleDateString()}</div>
                                </div>

                                {/* Evidence */}
                                <div className="flex-1 bg-black/30 rounded p-4 font-mono text-sm border border-neutral-800 w-full">
                                    {c.type === 'Indulgence' && (
                                        <div>
                                            <div className="text-green-500 mb-2">PAID: {c.amount}</div>
                                            <div className="text-neutral-500 BREAK-ALL">Tx: {c.evidence.txHash}</div>
                                        </div>
                                    )}
                                    {c.type === 'Ack' && (
                                        <div>
                                            <div className="text-blue-400 mb-2">" {c.evidence.tweetText} "</div>
                                            <div className="text-neutral-500">Source: Twitter API</div>
                                        </div>
                                    )}
                                </div>

                                {/* Badge */}
                                <div className="flex items-center justify-center">
                                    <span className="inline-block px-3 py-1 bg-yellow-900/20 text-yellow-500 border border-yellow-900 rounded text-xs font-bold uppercase tracking-wider">
                                        SAVED
                                    </span>
                                </div>

                            </div>
                        ))}

                        {conversions.length === 0 && (
                            <div className="text-center py-12 text-neutral-600 border border-dashed border-neutral-800 rounded-xl">
                                No conversions yet. The Crusade begins now.
                            </div>
                        )}
                    </div>
                )}
            </main>
        </div>
    );
}
