ALTER TABLE confessions ADD COLUMN IF NOT EXISTS "indulgencePrice" TEXT;
ALTER TABLE confessions ADD COLUMN IF NOT EXISTS "roast" TEXT;
ALTER TABLE confessions ADD COLUMN IF NOT EXISTS "sins" JSONB;
ALTER TABLE confessions ADD COLUMN IF NOT EXISTS "timestamp" TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE confessions ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'Sinner';
ALTER TABLE confessions ADD COLUMN IF NOT EXISTS "walletAddress" TEXT;
